#!/usr/bin/env python3
"""Amalgamate the modular public headers into a single self-contained header.

Run without arguments to (re)generate the single header at its default location:

    python3 generate_single_header.py

Local includes (headers found under the include root) are inlined exactly once so the result
is self-contained. External includes (system / other package headers) are kept as-is.

The original per-file include guards are preserved on purpose: the single header and the modular
headers share the same guard macros (HECTOR_ROS2_UTILS_*), so a translation unit may include both
the single header and the package headers without redefinition conflicts.
"""

import argparse
from datetime import datetime
import os
import re

# Paths derived from this script's location so it works without arguments.
REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
PACKAGE_DIR = os.path.join(REPO_ROOT, "hector_ros2_utils")

DEFAULT_ROOT = os.path.join(PACKAGE_DIR, "include")
DEFAULT_OUTPUT = os.path.join(REPO_ROOT, "dist", "hector_ros2_utils.hpp")
# Public headers to amalgamate, in include order. Dependencies are inlined automatically.
DEFAULT_HEADERS = [
    "hector_ros2_utils/utils/uuidv4.h",
    "hector_ros2_utils/parameters/reconfigurable_parameter.hpp",
    "hector_ros2_utils/node.hpp",
    "hector_ros2_utils/lifecycle_node.hpp",
]

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"]')
COMMENT_RE = re.compile(r"^\s*//")


def strip_leading_comment(lines):
    """Remove the leading copyright/comment block (and blank lines) but keep the include guard."""
    start = 0
    while start < len(lines) and (
        COMMENT_RE.match(lines[start]) or not lines[start].strip()
    ):
        start += 1
    return lines[start:]


def amalgamate(root, headers, output):
    visited = set()
    body = []

    def process(path):
        path = os.path.normpath(path)
        if path in visited:
            return
        visited.add(path)
        with open(path) as f:
            lines = f.read().splitlines()
        lines = strip_leading_comment(lines)
        body.append(f"// ===== {os.path.relpath(path, root)} =====")
        for line in lines:
            match = INCLUDE_RE.match(line)
            if match:
                target = os.path.join(root, match.group(2))
                if os.path.isfile(target):
                    # Local header: inline it (once) so the result is self-contained.
                    process(target)
                    continue
            # External includes, include guards and code are kept verbatim.
            body.append(line)
        body.append("")

    for header in headers:
        process(os.path.join(root, header))

    out = [
        "// This file is generated by generate_single_header.py. Do not edit.",
        "// It amalgamates all public headers of hector_ros2_utils into a single header.",
        f"// Version: {datetime.now().strftime('%Y.%m.%d-%H%M%S')}",
        "",
    ]
    out += body

    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w") as f:
        f.write("\n".join(out))


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--root",
        default=DEFAULT_ROOT,
        help="Include root directory. Default: package include/.",
    )
    parser.add_argument(
        "--output", default=DEFAULT_OUTPUT, help="Output header path. Default: dist/."
    )
    parser.add_argument(
        "headers",
        nargs="*",
        default=DEFAULT_HEADERS,
        help="Root headers relative to --root. Default: all public headers.",
    )
    args = parser.parse_args()
    amalgamate(args.root, args.headers, args.output)
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
